# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default
  #vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'MSDN'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az aks get-credentials --resource-group AzureRbac --name AzureRbac --overwrite-existing'


- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'MSDN'
    azureResourceGroup: 'AzureRbac'
    kubernetesCluster: 'AzureRbac'
    command: 'get'
    arguments: 'nodes'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'

- task: HelmDeploy@0
  inputs:
    azureContainerRegistry: 'JamieMsdn'
    azureResourceGroupForACR: 'AzureRbac'
    azureSubscriptionForACR: 'MSDN'
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'MSDN'
    azureResourceGroup: 'AzureRbac'
    kubernetesCluster: 'AzureRbac'
    command: 'ls'